version: '3.8'

services:
  mongodb:
    image: mongo:5
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build: .
    container_name: web-1
    ports:
      - "49160:49160"
    depends_on:
      mongodb:
        condition: service_healthy
    environment:
      DB_URL: mongodb://root:example@mongodb:27017/mydb?authSource=admin
    restart: unless-stopped  # Ensures container restarts if it crashes
